# Generated by Django 4.0 on 2021-12-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAdderss',
        ),
    ]
