# Generated by Django 4.0 on 2021-12-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_shippingadderss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
