# Generated by Django 4.0.1 on 2022-03-24 10:20

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='product/brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='category/banner/')),
                ('icon', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('searchable', models.BooleanField(default=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True)),
                ('searchable', models.BooleanField(default=True)),
                ('enable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('main_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], default='Percentage', max_length=10)),
                ('hot_deal_start', models.DateField(blank=True, null=True)),
                ('hot_deal_end', models.DateField(blank=True, null=True)),
                ('hot_deal_discount', models.IntegerField(blank=True, null=True)),
                ('hot_deal_discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hot_deal_free_shipping', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=3)),
                ('short_info', models.TextField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('additional_info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('shipping_info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=500, null=True)),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None), blank=True, null=True, size=None)),
                ('enable', models.BooleanField(default=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('related_product', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique', models.TextField(blank=True, null=True)),
                ('total_view', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categorys', to='product.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_groups', to='product.group')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True)),
                ('searchable', models.BooleanField(default=True)),
                ('enable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategorys', to='product.group')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('add_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_create', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_subcategorys', to='product.subcategory'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.TextField(blank=True)),
                ('unique', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product')),
            ],
        ),
    ]
