# Generated by Django 4.0 on 2022-01-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_recentyview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentyView',
            new_name='RecentlyView',
        ),
    ]
