# Generated by Django 4.0 on 2022-01-26 04:53

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_recentyview_recentlyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
