# Generated by Django 4.0.1 on 2022-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_options_alter_product_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='style',
            field=models.CharField(default='dropdown', max_length=100),
            preserve_default=False,
        ),
    ]
