# Generated by Django 4.0.1 on 2022-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
