# Generated by Django 4.0.1 on 2022-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='logo',
            field=models.ImageField(upload_to='product/brand/'),
        ),
    ]
