# Generated by Django 4.0.1 on 2022-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_brands_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.ManyToManyField(to='product.Option'),
        ),
    ]
