# Generated by Django 4.0 on 2021-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_deal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
