# Generated by Django 3.2.13 on 2022-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_option_parent_name_alter_options_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
