# Generated by Django 4.0.1 on 2022-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_add_on_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='unique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
