# Generated by Django 4.0.1 on 2022-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_images_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
