# Generated by Django 4.0.1 on 2022-02-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_keywords_product_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hot_deal',
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
