# Generated by Django 4.0 on 2021-12-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subategory',
            new_name='Subcategory',
        ),
    ]
