# Generated by Django 4.0 on 2021-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_subategory_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='category/banner/'),
        ),
    ]
