# Generated by Django 4.0.1 on 2022-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
