# Generated by Django 3.2.13 on 2022-04-30 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='emails',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), null=True, size=None), null=True, size=None),
        ),
    ]
