# Generated by Django 4.0.1 on 2022-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_addressbook_area_alter_addressbook_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
