# Generated by Django 4.0.1 on 2022-03-15 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_addressbook_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
