# Generated by Django 3.2.3 on 2021-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='shopinfo')),
                ('favicon', models.ImageField(upload_to='shopinfo')),
            ],
        ),
    ]
