# Generated by Django 3.2.3 on 2021-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='youtube',
            field=models.URLField(),
        ),
    ]
