# Generated by Django 4.0.1 on 2022-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
