# Generated by Django 3.2.3 on 2021-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
