# Generated by Django 4.0 on 2021-12-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_group_category_subcategory_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
