# Generated by Django 4.0 on 2021-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.TextField(verbose_name='Line 1')),
                ('line_2', models.TextField(verbose_name='Line 2')),
                ('line_3', models.TextField(verbose_name='Line 3')),
                ('image', models.ImageField(upload_to='slide/')),
                ('active', models.BooleanField(verbose_name='Status')),
            ],
        ),
    ]
