# Generated by Django 4.0 on 2021-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('banner', models.ImageField(upload_to='aboutus/banner')),
            ],
        ),
    ]
