# Generated by Django 4.0 on 2021-12-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutus_teaminfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
    ]
