# Generated by Django 4.0 on 2021-12-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='Note',
            new_name='note',
        ),
    ]
