# Generated by Django 4.0 on 2021-12-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_note_contactmessage_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
