# Generated by Django 4.0.1 on 2022-04-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
