# Generated by Django 4.0 on 2022-01-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
