# Generated by Django 4.0.1 on 2022-03-24 10:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('banner', models.ImageField(upload_to='aboutus/banner')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption1', models.CharField(blank=True, max_length=500, null=True)),
                ('caption2', models.CharField(blank=True, max_length=500, null=True)),
                ('caption3', models.CharField(blank=True, max_length=500, null=True)),
                ('call_to_text', models.CharField(default='Shop Now', max_length=500)),
                ('call_to_url', models.CharField(default='/', max_length=500)),
                ('image', models.ImageField(upload_to='banner/')),
                ('banner_type', models.CharField(choices=[('banner1', 'banner1'), ('banner2', 'banner2'), ('banner3', 'banner3'), ('banner4', 'banner4'), ('banner5', 'banner5'), ('banner6', 'banner6'), ('banner4', 'banner7'), ('banner8', 'banner8')], default='Top', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('speed', models.IntegerField(default=3000)),
                ('autoplay', models.BooleanField(default=True)),
                ('autoplay_timeout', models.IntegerField(default=4000)),
                ('dots', models.BooleanField(default=True)),
                ('arrows', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='aboutus/team/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_1', models.CharField(max_length=250, verbose_name='caption 1')),
                ('caption_2', models.CharField(max_length=250, verbose_name='caption 2')),
                ('caption_3', models.CharField(max_length=250, verbose_name='caption 3')),
                ('action_text', models.CharField(max_length=200, verbose_name='Call to Action Text')),
                ('action_url', models.URLField(verbose_name='Call to Action URL')),
                ('link_type', models.BooleanField(verbose_name='Open in new window')),
                ('image', models.ImageField(upload_to='slide/')),
                ('active', models.BooleanField(verbose_name='Status')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='setting.slider')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buy Now', max_length=255)),
                ('phone', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('logo', models.ImageField(default='settings/logo.png', upload_to='settings/')),
                ('address', models.CharField(default='Dhaka', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter', models.URLField(default='twitter.com')),
                ('facebook', models.URLField(default='facebook.com')),
                ('youtube', models.URLField(default='youtube.com')),
                ('instagram', models.URLField(default='instagram.com')),
                ('favicon', models.ImageField(upload_to='settings/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('banner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner1', to='setting.banner')),
                ('banner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner2', to='setting.banner')),
                ('banner3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner3', to='setting.banner')),
                ('banner4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner4', to='setting.banner')),
                ('banner5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner5', to='setting.banner')),
                ('banner6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner6', to='setting.banner')),
                ('banner7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner7', to='setting.banner')),
                ('banner8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner8', to='setting.banner')),
                ('privacy_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privacy_policy', to='setting.pages')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setting.slider')),
                ('term_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='term_condition', to='setting.pages')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, to='product.Category')),
                ('groups', models.ManyToManyField(blank=True, to='product.Group')),
                ('subcategorys', models.ManyToManyField(blank=True, to='product.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('mega', 'Mega Menu'), ('dropdown', 'Dropdown')], max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('categorys', models.ManyToManyField(to='product.Category')),
                ('groups', models.ManyToManyField(to='product.Group')),
                ('subcategorys', models.ManyToManyField(to='product.Subcategory')),
            ],
        ),
    ]
