# Generated by Django 4.0 on 2022-01-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('banner', models.ImageField(upload_to='aboutus/banner')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner/')),
                ('banner_type', models.CharField(choices=[('Left', 'Left'), ('Top', 'Top'), ('Middle Small', 'Middle Small'), ('Middle Big', 'Middle Big'), ('Bottom', 'Bottom')], default='Top', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Buy Now', max_length=255)),
                ('phone', models.CharField(default=1, max_length=20)),
                ('logo', models.ImageField(default='settings/logo.png', upload_to='settings/')),
                ('address', models.CharField(default='Dhaka', max_length=200)),
                ('twitter', models.URLField(default='twitter.com')),
                ('facebook', models.URLField(default='facebook.com')),
                ('youtube', models.URLField(default='youtube.com')),
                ('instagram', models.URLField(default='instagram.com')),
                ('favicon', models.ImageField(upload_to='settings/')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('autoplay', models.BooleanField(default=True)),
                ('autoplay_timeout', models.IntegerField(default=4000)),
                ('arrows', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='aboutus/team/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_1', models.CharField(max_length=250, verbose_name='caption 1')),
                ('caption_2', models.CharField(max_length=250, verbose_name='caption 2')),
                ('caption_3', models.CharField(max_length=250, verbose_name='caption 3')),
                ('action_text', models.CharField(max_length=200, verbose_name='Call to Action Text')),
                ('action_url', models.URLField(verbose_name='Call to Action URL')),
                ('link_type', models.BooleanField(verbose_name='Open in new window')),
                ('image', models.ImageField(upload_to='slide/')),
                ('active', models.BooleanField(verbose_name='Status')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='setting.slider')),
            ],
        ),
        migrations.CreateModel(
            name='SiteFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_banner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottom_banner1', to='setting.banner')),
                ('bottom_banner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottom_banner2', to='setting.banner')),
                ('left_banner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_banner1', to='setting.banner')),
                ('left_banner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_banner2', to='setting.banner')),
                ('middle_big_banner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='middle_big_banner1', to='setting.banner')),
                ('middle_big_banner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='middle_big_banner2', to='setting.banner')),
                ('middle_small_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='middle_small_banner', to='setting.banner')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setting.slider')),
                ('top_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_banner', to='setting.banner')),
            ],
            options={
                'verbose_name': 'Site Front',
            },
        ),
    ]
