# Generated by Django 4.0 on 2021-12-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='about_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setting.aboutus'),
            preserve_default=False,
        ),
    ]
