# Generated by Django 4.0.1 on 2022-04-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol_native', models.CharField(max_length=5)),
                ('decimal_digits', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=10)),
                ('name_plural', models.CharField(max_length=100)),
            ],
        ),
    ]
