# Generated by Django 4.0 on 2021-12-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_teaminfo_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliding',
            options={'verbose_name': 'myapp'},
        ),
    ]
