# Generated by Django 4.0 on 2022-01-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('setting', '0002_productcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarousel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='product.Group'),
        ),
        migrations.AddField(
            model_name='productcarousel',
            name='subcategorys',
            field=models.ManyToManyField(blank=True, to='product.Subcategory'),
        ),
        migrations.AlterField(
            model_name='productcarousel',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
    ]
