# Generated by Django 4.0 on 2022-01-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_productcarousel_groups_productcarousel_subcategorys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcarousel',
            old_name='Enable Carousel',
            new_name='enable',
        ),
    ]
