# Generated by Django 4.0 on 2021-12-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_sliding_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliding',
            options={'verbose_name': 'Sliders'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='big_banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', max_length=30),
        ),
    ]
