# Generated by Django 4.0.1 on 2022-04-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
