# Generated by Django 4.0 on 2022-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_recentyview_recentlyview'),
        ('setting', '0004_rename_enable carousel_productcarousel_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=200)),
                ('categorys', models.ManyToManyField(to='product.Category')),
            ],
        ),
    ]
