# Generated by Django 4.0.1 on 2022-04-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_currency_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=200)),
                ('email_port', models.CharField(max_length=20)),
                ('email_use', models.CharField(max_length=10)),
                ('email_host_user', models.CharField(max_length=100)),
                ('email_host_password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_email', models.BooleanField(default=True)),
                ('order_email', models.BooleanField(default=True)),
                ('order_status_email', models.BooleanField(default=True)),
                ('invoice_email', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defailt_currency', to='setting.currency')),
                ('supported_currency', models.ManyToManyField(related_name='supported_currency', to='setting.Currency')),
            ],
        ),
    ]
