# Generated by Django 4.0 on 2021-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_sliding_options_remove_banner_big_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Left_1', 'Left1'), ('Left_2', 'Left2'), ('Right_1', 'Right1'), ('Right_2', 'Right2'), ('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', max_length=30),
        ),
    ]
