# Generated by Django 4.0 on 2021-12-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Left_1', 'Left 1'), ('Left_2', 'Left 2'), ('Right_1', 'Right 1'), ('Right_2', 'Right 2'), ('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', max_length=30),
        ),
    ]
