# Generated by Django 4.0 on 2022-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='style',
            field=models.CharField(choices=[('Mega', 'Mega Menu'), ('Dropdown', 'Dropdown')], max_length=200),
        ),
    ]
