# Generated by Django 4.0.1 on 2022-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_emailconfig_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=300)),
                ('icon1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=300)),
                ('subtitle2', models.CharField(max_length=300)),
                ('icon2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=300)),
                ('subtitl3', models.CharField(max_length=300)),
                ('icon3', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
