# Generated by Django 4.0.1 on 2022-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='subtitl4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
