# Generated by Django 4.0 on 2022-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_recentyview_recentlyview'),
        ('setting', '0006_alter_menus_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='groups',
            field=models.ManyToManyField(blank=True, to='product.Group'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='style',
            field=models.CharField(choices=[('mega', 'Mega Menu'), ('dropdown', 'Dropdown')], max_length=200),
        ),
    ]
