# Generated by Django 4.0 on 2021-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_banner_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dhaka', 1), ('Mymensingh', 2), ('Sylhet', 3)], max_length=10)),
            ],
        ),
    ]
