# Generated by Django 4.0 on 2021-12-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[(1, 'Barishal'), (2, 'Chattogram'), (3, 'Dhaka'), (4, 'Khulna'), (5, 'Rajshahi'), (6, 'Rangpur'), (7, 'Sylhet'), (8, 'Mymensingh')], max_length=50),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Barishal'), (2, 'Chattogram'), (3, 'Dhaka'), (4, 'Khulna'), (5, 'Rajshahi'), (6, 'Rangpur'), (7, 'Sylhet'), (8, 'Mymensingh')], max_length=50)),
                ('divisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.region')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Barishal'), (2, 'Chattogram'), (3, 'Dhaka'), (4, 'Khulna'), (5, 'Rajshahi'), (6, 'Rangpur'), (7, 'Sylhet'), (8, 'Mymensingh')], max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.city')),
                ('divisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.region')),
            ],
        ),
    ]
