# Generated by Django 4.0 on 2022-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_recentyview_recentlyview'),
        ('setting', '0007_menus_groups_alter_menus_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
    ]
