# Generated by Django 4.0.1 on 2022-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_feature_icon4_feature_subtitl4_feature_title4'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='subtitle1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
