# Generated by Django 4.0 on 2022-01-26 14:52

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_menus_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
