# Generated by Django 4.0 on 2021-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_region_name_city_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Buy Now', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('1', 'Barishal'), ('2', 'Chattogram'), ('3', 'Dhaka'), ('4', 'Khulna'), ('5', 'Rajshahi'), ('6', 'Rangpur'), ('7', 'Sylhet'), ('8', 'Mymensingh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('1', 'Barishal'), ('2', 'Chattogram'), ('3', 'Dhaka'), ('4', 'Khulna'), ('5', 'Rajshahi'), ('6', 'Rangpur'), ('7', 'Sylhet'), ('8', 'Mymensingh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('1', 'Barishal'), ('2', 'Chattogram'), ('3', 'Dhaka'), ('4', 'Khulna'), ('5', 'Rajshahi'), ('6', 'Rangpur'), ('7', 'Sylhet'), ('8', 'Mymensingh')], max_length=50),
        ),
    ]
