# Generated by Django 4.0.1 on 2022-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_feature_subtitle1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='subtitl3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
