# Generated by Django 4.0.1 on 2022-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_alter_feature_icon1_alter_feature_icon2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='subtitl3',
            new_name='subtitle3',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='subtitl4',
            new_name='subtitle4',
        ),
    ]
