# Generated by Django 4.0 on 2021-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_siteconfiguration_site_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(default='/media/settings/logo.png', upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_phone',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
