# Generated by Django 4.0.1 on 2022-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_menus_active_remove_menus_categorys_menus_categorys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
