# Generated by Django 4.0.1 on 2022-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_links_storeinfo_footerlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
