# Generated by Django 4.0 on 2021-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_alter_siteconfiguration_site_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='site_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='site_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_logo',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(default='Dhaka', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook',
            field=models.URLField(default='facebook.com'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(default=1, upload_to='settings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram',
            field=models.URLField(default='instagram.com'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(default='settings/logo.png', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter',
            field=models.URLField(default='twitter.com'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube',
            field=models.URLField(default='youtube.com'),
        ),
    ]
