# Generated by Django 4.0.1 on 2022-02-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_option'),
        ('setting', '0012_alter_menus_categorys_alter_menus_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='subcategorys',
            field=models.ManyToManyField(to='product.Subcategory'),
        ),
        migrations.RemoveField(
            model_name='menus',
            name='categorys',
        ),
        migrations.AddField(
            model_name='menus',
            name='categorys',
            field=models.ManyToManyField(to='product.Category'),
        ),
        migrations.RemoveField(
            model_name='menus',
            name='groups',
        ),
        migrations.AddField(
            model_name='menus',
            name='groups',
            field=models.ManyToManyField(to='product.Group'),
        ),
    ]
