# Generated by Django 4.0.1 on 2022-04-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_links_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarousel',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
