# Generated by Django 4.0 on 2021-12-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_rename_site_name_siteconfiguration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('1', 'Barishal'), ('2', 'Chattogram'), ('3', 'Dhaka'), ('4', 'Khulna'), ('5', 'Rajshahi'), ('6', 'Rangpur'), ('7', 'Sylhet'), ('8', 'Mymensingh')], max_length=50, unique=True),
        ),
    ]
