# Generated by Django 4.0.1 on 2022-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_menus_subcategorys_remove_menus_categorys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='dots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='speed',
            field=models.IntegerField(default=3000),
        ),
    ]
