# Generated by Django 4.0 on 2021-12-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_alter_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_3', models.CharField(max_length=250, verbose_name='caption 1')),
                ('caption_2', models.CharField(max_length=250, verbose_name='caption 3')),
                ('action_text', models.CharField(max_length=200, verbose_name='Call to Action Text')),
                ('action_url', models.URLField(verbose_name='Call to Action URL')),
                ('link_type', models.BooleanField(verbose_name='Open in new window')),
                ('image', models.ImageField(upload_to='slide/')),
                ('active', models.BooleanField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='SliderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True)),
                ('arrows', models.BooleanField(default=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='setting.slider')),
            ],
            options={
                'verbose_name': 'Settings',
            },
        ),
        migrations.DeleteModel(
            name='Sliding',
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='setting.slider'),
        ),
    ]
