# Generated by Django 4.0.1 on 2022-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_slider_dots_slider_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
