# Generated by Django 4.0 on 2021-12-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_slide_slider_slidersetting_delete_sliding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersetting',
            name='slider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.slider'),
        ),
    ]
