# Generated by Django 4.0.1 on 2022-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_slide_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
