# Generated by Django 4.0.1 on 2022-03-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefront',
            name='bottom_banner1',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='bottom_banner2',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='left_banner1',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='left_banner2',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='middle_big_banner1',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='middle_big_banner2',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='middle_small_banner',
        ),
        migrations.RemoveField(
            model_name='sitefront',
            name='top_banner',
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner1', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner2', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner3', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner4', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner5', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner6', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner7', to='setting.banner'),
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner8', to='setting.banner'),
        ),
    ]
