# Generated by Django 4.0 on 2021-12-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_sitefront'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
