# Generated by Django 4.0.1 on 2022-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_remove_sitefront_bottom_banner1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='call_to_text',
            field=models.CharField(default='Shop Now', max_length=500),
        ),
        migrations.AddField(
            model_name='banner',
            name='call_to_url',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.AddField(
            model_name='banner',
            name='caption1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='caption2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='caption3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('banner1', 'banner1'), ('banner2', 'banner2'), ('banner3', 'banner3'), ('banner4', 'banner4'), ('banner5', 'banner5'), ('banner6', 'banner6'), ('banner4', 'banner7'), ('banner8', 'banner8')], default='Top', max_length=50),
        ),
    ]
