# Generated by Django 4.0 on 2021-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_delete_shopinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='caption_1',
            field=models.CharField(default=1, max_length=250, verbose_name='caption 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='caption_2',
            field=models.CharField(max_length=250, verbose_name='caption 2'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='caption_3',
            field=models.CharField(max_length=250, verbose_name='caption 3'),
        ),
    ]
