# Generated by Django 4.0 on 2021-12-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_slide_caption_1_alter_slide_caption_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersetting',
            name='slider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='setting.slider'),
        ),
    ]
