# Generated by Django 4.0 on 2022-01-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0022_slider_arrows_slider_autoplay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AddField(
            model_name='sitefront',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setting.banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Left', 'Left'), ('Top', 'Top'), ('Middle Small', 'Middle Small'), ('Middle Big', 'Middle Big'), ('Bottom', 'Bottom')], default='Top', max_length=50),
        ),
    ]
