# Generated by Django 4.0 on 2022-01-02 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_profile'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percent', 'Percent')], default='Percent', max_length=20)),
                ('value', models.IntegerField()),
                ('Allow free shipping', models.BooleanField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_spend', models.IntegerField(blank=True, null=True)),
                ('max_spend', models.IntegerField(blank=True, null=True)),
                ('Exclude Categories', models.ManyToManyField(blank=True, related_name='coupon_exclude_categories', to='product.Category')),
                ('Exclude Products', models.ManyToManyField(blank=True, related_name='coupon_exclude_products', to='product.Product')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupon_categories', to='product.Category')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
                ('products', models.ManyToManyField(blank=True, related_name='coupon_products', to='product.Product')),
            ],
            options={
                'verbose_name': 'User Restriction',
            },
        ),
        migrations.CreateModel(
            name='UserLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_per_coupon', models.IntegerField(blank=True, null=True)),
                ('limit_per_customer', models.IntegerField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
            ],
            options={
                'verbose_name': 'User Limit',
            },
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
