# Generated by Django 4.0.1 on 2022-02-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Allow free shipping',
            new_name='free_shipping',
        ),
    ]
