# Generated by Django 4.0 on 2021-12-17 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_detail'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percent', 'Percent')], max_length=20)),
                ('value', models.IntegerField()),
                ('Allow free shipping', models.BooleanField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_spend', models.IntegerField(blank=True)),
                ('max_spend', models.IntegerField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='coupon_categories', to='product.Category')),
                ('coupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
                ('exclude_categories', models.ManyToManyField(blank=True, related_name='coupon_exclude_categories', to='product.Category')),
                ('exclude_products', models.ManyToManyField(blank=True, related_name='coupon_exclude_products', to='product.Product')),
                ('products', models.ManyToManyField(blank=True, related_name='coupon_products', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='UserLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_per_coupon', models.IntegerField()),
                ('limit_per_customer', models.IntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
            ],
        ),
    ]
