# Generated by Django 4.0 on 2021-12-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_coupon_userrestrictions_userlimits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlimits',
            options={'verbose_name': 'User Limit'},
        ),
        migrations.AlterModelOptions(
            name='userrestrictions',
            options={'verbose_name': 'User Restriction'},
        ),
        migrations.RenameField(
            model_name='userrestrictions',
            old_name='coupom',
            new_name='coupon',
        ),
    ]
