# Generated by Django 4.0.1 on 2022-03-30 03:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shopcart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
    ]
