# Generated by Django 4.0 on 2021-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_userlimits_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrestrictions',
            old_name='exclude_categories',
            new_name='Exclude Categories',
        ),
        migrations.RenameField(
            model_name='userrestrictions',
            old_name='exclude_products',
            new_name='Exclude Products',
        ),
        migrations.AlterField(
            model_name='userlimits',
            name='limit_per_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlimits',
            name='limit_per_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrestrictions',
            name='max_spend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrestrictions',
            name='min_spend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
