# Generated by Django 4.0.1 on 2022-04-09 06:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_brands_logo'),
        ('order', '0004_alter_shopcart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='options',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None), size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='shopcart',
            name='carts',
            field=models.ManyToManyField(to='order.Cart'),
        ),
    ]
