# Generated by Django 4.0.1 on 2022-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shippingmethod_alter_shopcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='method_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
