# Generated by Django 4.0 on 2021-12-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shopcart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Percent', 'Percent')], default='Percent', max_length=20),
        ),
    ]
