# Generated by Django 4.0.1 on 2022-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_shopcart_options_remove_shopcart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='coupon',
            field=models.ManyToManyField(to='order.Coupon'),
        ),
    ]
