# Generated by Django 4.0.1 on 2022-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_user_id_order_payment_mode_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='on_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
