# Generated by Django 4.0.1 on 2022-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shopcart_on_order_shopcart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopcarts',
            field=models.ManyToManyField(to='order.ShopCart'),
        ),
    ]
