# Generated by Django 4.0.1 on 2022-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_brands_logo'),
        ('order', '0008_alter_shopcart_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='options',
        ),
        migrations.AddField(
            model_name='cart',
            name='options',
            field=models.ManyToManyField(to='product.Option'),
        ),
    ]
