# Generated by Django 4.0.1 on 2022-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_date_order_status_order_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('processing', 'Processing')], default='Processing', max_length=200),
        ),
    ]
