# Generated by Django 4.0.1 on 2022-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('pending', 'Pending'), ('pending_payment', 'Pending Payment')], default='processing', max_length=200),
        ),
    ]
