# Generated by Django 4.0.1 on 2022-04-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
