# Generated by Django 4.0.1 on 2022-04-22 02:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_coupon_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_cost',
            new_name='coupon_disc',
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
