# Generated by Django 4.0.1 on 2022-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_address_book_order_area_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_bst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
