# Generated by Django 4.0.1 on 2022-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_rename_coupon_cost_order_coupon_disc_order_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
    ]
