# Generated by Django 4.0.1 on 2022-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_rate_order_total_bst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_bst',
            new_name='total_bdt',
        ),
    ]
