# Generated by Django 4.0.1 on 2022-04-24 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_option_parent_name_alter_options_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0015_order_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
