# Generated by Django 3.2.13 on 2022-04-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_wishlist_device_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='carts',
            field=models.ManyToManyField(related_name='parents', to='order.Cart'),
        ),
    ]
