# Generated by Django 4.0.1 on 2022-03-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_shopcarts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_method',
            new_name='shipping_method',
        ),
    ]
