# Generated by Django 4.0.1 on 2022-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_rename_shipping_method_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopcarts',
            field=models.ManyToManyField(to='order.ShopCart'),
        ),
    ]
