# Generated by Django 4.0.1 on 2022-03-21 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_shopcarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
