# Generated by Django 4.0.1 on 2022-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
