# Generated by Django 4.0.1 on 2022-03-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_paymentmethod_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='cliend_id',
            new_name='client_id',
        ),
    ]
