# Generated by Django 4.0.1 on 2022-03-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_rate'),
        ('order', '0022_rename_cliend_id_paymentmethod_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='product.Category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_categories',
            field=models.ManyToManyField(related_name='exclude_categories', to='product.Category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_products',
            field=models.ManyToManyField(related_name='exclude_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_spend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_spend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(related_name='products', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
